// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzW2fjE-RIm-_1tb-VRUhQwbb9At5gR0w',
    appId: '1:373644372568:web:fcd5b6c31c4dc79a44b82d',
    messagingSenderId: '373644372568',
    projectId: 'dynamic-courier',
    authDomain: 'dynamic-courier.firebaseapp.com',
    storageBucket: 'dynamic-courier.appspot.com',
    measurementId: 'G-22Z1X7VZYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5o-ajf53l4Wo_MKAA7JNElVJwYM_bAk',
    appId: '1:373644372568:android:bf8d95771e74f22b44b82d',
    messagingSenderId: '373644372568',
    projectId: 'dynamic-courier',
    storageBucket: 'dynamic-courier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DVLccjFg6InCicP3DuO-8HfzJkc-hxo',
    appId: '1:373644372568:ios:59680a695011f8f944b82d',
    messagingSenderId: '373644372568',
    projectId: 'dynamic-courier',
    storageBucket: 'dynamic-courier.appspot.com',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1DVLccjFg6InCicP3DuO-8HfzJkc-hxo',
    appId: '1:373644372568:ios:b61ed06ad857ccf844b82d',
    messagingSenderId: '373644372568',
    projectId: 'dynamic-courier',
    storageBucket: 'dynamic-courier.appspot.com',
    iosBundleId: 'com.example.flutterProjects.RunnerTests',
  );
}
